### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'robot.txt'

### ISSUE THREAD

**Issue by riramar** [the-c0d3r/admin-finder#7]
root@zion:~/Tools/admin-finder# python3 admin-finder.py -u https://_ _ _ _ _ _.com

    ╔════════════════════════════════════════════╗
    ║               .          .                 ║
    ║ ,-. ,-| ,-,-. . ,-.   ," . ,-. ,-| ,-. ,-. ║
    ║ ,-| | | | | | | | |   |- | | | | | |-' |   ║
    ║ `-^ `-^ ' ' ' ' ' '   |  ' ' ' `-^ `-' '   ║
    ║                       '          the-c0d3r ║
    ╚════════════════════════════════════════════╝
    
Traceback (most recent call last):
  File "admin-finder.py", line 93, in <module>
    main()
  File "admin-finder.py", line 43, in main
    robot_handler = RobotHandler(args.url)
  File "/root/Tools/admin-finder/lib/connection.py", line 67, in __init__
    self.keywords = [line.strip('\n') for line in open('robot.txt').readlines()]
FileNotFoundError: [Errno 2] No such file or directory: 'robot.txt'
root@zion:~/Tools/admin-finder#

**Comment by the-c0d3r** [comment]
Hey, thanks for the issue. I totally forgotten to commit the `robot.txt` file. Now you can do a `git pull` and it should work again.

**Comment by riramar** [comment]
Seems the robot.txt issue has been fixed but you have another problem.

```
root@zion:~/Tools/admin-finder# python3 admin-finder.py -u https://www.google.com

    ╔════════════════════════════════════════════╗
    ║               .          .                 ║
    ║ ,-. ,-| ,-,-. . ,-.   ," . ,-. ,-| ,-. ,-. ║
    ║ ,-| | | | | | | | |   |- | | | | | |-' |   ║
    ║ `-^ `-^ ' ' ' ' ' '   |  ' ' ' `-^ `-' '   ║
    ║                       '          the-c0d3r ║
    ╚════════════════════════════════════════════╝
    
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f3120b896d8>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='https', port=80): Max retries exceeded with url: //www.google.com/robot.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3120b896d8>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "admin-finder.py", line 93, in <module>
    main()
  File "admin-finder.py", line 44, in main
    result = robot_handler.scan()
  File "/root/Tools/admin-finder/lib/connection.py", line 84, in scan
    result = self.connect(link)
  File "/root/Tools/admin-finder/lib/connection.py", line 28, in connect
    request = requests.get(url, headers=self.get_headers())
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='https', port=80): Max retries exceeded with url: //www.google.com/robot.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3120b896d8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
root@zion:~/Tools/admin-finder# 

```

**Comment by riramar** [comment]
This doesn't make sense >>> `HTTPConnectionPool(host='https', port=80)`

**Comment by the-c0d3r** [comment]
Hey there, take a look at my latest changes on master. Apparently I forgotten to handle the check for "https". Let me know if there's any more issues.

**Comment by the-c0d3r** [comment]
Feel free to reopen this if the issue still occurs. 

I'll assume it's fixed and close it.
